### ISSUE TITLE
Filepath relative to module

### ISSUE THREAD

**Issue by aureliensibiril** [katzien/go-structure-examples#11]
This repository gave me lot's of inspiration for my own projects but I do have one question regarding filepath.

Let's say you have a static file ( html file or other) in your "rest" package, how would you link to this file from your handler.go file ?

**Comment by katzien** [comment]
Hey @aureliensibiril, sorry for missing your message earlier.
Not sure I understand your question :). What would the static file do? This is an API not a website so putting static files like css / images etc doesn't make much sense? Or am I missing something?
