### ISSUE TITLE
Different use case

### ISSUE THREAD

**Issue by theobouwman** [katzien/go-structure-examples#3]
Hello,

I am trying to implement this structure for a new project.

What I first tried was creating a `listing` and `register` service for users.
But I am getting to the point where I want to `GetAUserByEmail` in order to check if a user is already registered with that email.

So should I use the `listing`.`GetUserByEmail` in the `register` service or definitely not?

Like here:
- clone `https://gitlab.com/theobouwman98/wp/tree/hex-impl`
- run `go run cmd/register-server/main.go`

What would be a good fix for this.

Thanks in advance.

**Comment by theobouwman** [comment]
@katzien ?

**Comment by katzien** [comment]
Hi @theobouwman!

I can't access your link (needs me to sign in), but it sounds like maybe you should have a `users` module which would provide a `GetUserByEmail` function which can then be used by both `listing` and `register`? That's all I can say without knowing what your project is about :)

**Comment by theobouwman** [comment]
Thanks. Found another solution!

**Comment by katzien** [comment]
What did you end up doing? :)
