### ISSUE TITLE
Add link to readme

### ISSUE THREAD

**Issue by mbitokhov** [katzien/go-structure-examples#6]
Hi!

I found this repository from duckduckgo. Can you add a readme with the link to the talk? I'd make a pull request but I don't feel too comfortable writing something on behalf of you

 I managed to find a link to it on youtube
https://www.youtube.com/watch?v=oL6JBUk6tj0

Thanks,

**Comment by katzien** [comment]
Done! Thanks for the suggestion @mbitokhov!
